m1 = matrix(1:20,nrow=5, ncol=4)
print("5 x 4 martix:")
print(m1)
cells = c(1,3,5,7,8,9,11,12,14)
rnames = c("Row1","Row2", "Row3")
cnames = c("col1", "col2", "col3")
m2 = matrix(cells, nrow=3, ncol=3, byrow=TRUE,dimnames=list(rnames, cnames))
print("3 x 3 matrix with labels, filled by rows: ")
print(m2)
print("3 x3 matrix with labels, filled by colomns:")
m3 = matrix(cells, nrow=3, ncol=3, byrow=FALSE,dimnames=list(rnames, cnames))
print(m3)

